{{- if .Values.pgsql_mailman_recipients.create -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.pgsql_mailman_recipients.name }}
  labels:
    {{- include "postfix.labels" . | nindent 4 }}
type: Opaque
data:
  pgsql-mailman-recipients.cf: {{ .Values.pgsql_mailman_recipients.data.pgsql_mailman_recipients.cf | b64enc }}
{{- end }}
