{{- if .Values.pgsql_transport_mm.create -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.pgsql_transport_mm.name }}
  labels:
    {{- include "postfix.labels" . | nindent 4 }}
type: Opaque
data:
  pgsql-transport-mm.cf: {{ .Values.pgsql_transport_mm.data.pgsql_transport_mm | b64enc }}
{{- end }}
