{{- if .Values.pgsql_transport.create -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.pgsql_transport.name }}
  labels:
    {{- include "postfix.labels" . | nindent 4 }}
type: Opaque
data:
  ppgsql-transport.cf: {{ .Values.pgsql_transport.data.pgsql_transport.cf | b64enc }}
{{- end }}
