{{- if .Values.pgsql_virtual_recipients.create -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.pgsql_virtual_recipients.name | replace "_" "-"}}
  labels:
    {{- include "postfix.labels" . | nindent 4 }}
type: Opaque
data:
  pgsql-virtual-recipients.cf: {{ .Values.pgsql_virtual_recipients.data.pgsql_virtual_recipients | b64enc }}
{{- end }}
