{{- if .Values.pgsql_relay_domains_mm.create -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.pgsql_relay_domains_mm.name }}
  labels:
    {{- include "postfix.labels" . | nindent 4 }}
type: Opaque
data:
  pgsql_relay_domains_mm.cf: {{ .Values.pgsql_relay_domains_mm.data.pgsql_relay_domains_mm.cf | b64enc }}
{{- end }}
