{{- if .Values.pgsql_relay_domains.create -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.pgsql_relay_domains.name }}
  labels:
    {{- include "postfix.labels" . | nindent 4 }}
type: Opaque
data:
  pgsql-relay-domains.cf: {{ .Values.pgsql_relay_domains.data.pgsql_relay_domains.cf | b64enc }}
{{- end }}
