{{- if .Values.pgsql_restricted_senders.create -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.pgsql_restricted_senders.name | replace "_" "-" }}
  labels:
    {{- include "postfix.labels" . | nindent 4 }}
type: Opaque
data:
  pgsql-restricted-senders.cf: {{ .Values.pgsql_restricted_senders.data.pgsql_restricted_senders | b64enc }}
{{- end }}
