{{- if .Values.mx_tls.create -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.mx_tls.name }}
  labels:
    {{- include "postfix.labels" . | nindent 4 }}
type: Opaque
data:
  mx-tls: {{ .Values.mx_tls.data.mx_tls | b64enc }}
{{- end }}
