pgsql_transport:
  create: false
  name: pgsql_transport
  postscreenEnabled: true
  data:
    pgsql_transport: |
      user         = my_db_user
      password     = my_db_pass
      dbname       = my_db_name
      hosts        = my_db_host
      query        = select email from mailman_recipients where email = '%s'

pgsql_transport_mm:
  create: false
  name: pgsql_transport_mm
  data:
    pgsql_transport_mm: |
      user         = my_db_user
      password     = my_db_pass
      dbname       = my_db_name
      hosts        = my_db_host
      query        = select email from mailman_recipients where email = '%s'

pgsql_relay_domains_mm:
  create: false
  name: pgsql_relay_domains_mm
  data:
    pgsql_relay_domains_mm: |
      user         = my_db_user
      password     = my_db_pass
      dbname       = my_db_name
      hosts        = my_db_host
      query        = select email from mailman_recipients where email = '%s'

pgsql_relay_domains:
  create: false
  name: pgsql_relay_domains
  data:
    pgsql_relay_domains: |
      user         = my_db_user
      password     = my_db_pass
      dbname       = my_db_name
      hosts        = my_db_host
      query        = select email from mailman_recipients where email = '%s'

pgsql_mailman_recipients:
  create: false
  name: pgsql_mailman_recipients
  data:
    pgsql_mailman_recipients: |
      user         = my_db_user
      password     = my_db_pass
      dbname       = my_db_name
      hosts        = my_db_host
      query        = select email from mailman_recipients where email = '%s'

pgsql_virtual_recipients:
  create: false
  name: pgsql_mailman_recipients
  data:
    pgsql_mailman_recipients: |
      user         = my_db_user
      password     = my_db_pass
      dbname       = my_db_name
      hosts        = my_db_host
      query        = select email from mailman_recipients where email = '%s'

pgsql_virtual:
  create: false
  name: pgsql-virtual
  data:
    pgsql_virtual: |
      user         = my_db_user
      password     = my_db_pass
      dbname       = my_db_name
      hosts        = my_db_host
      query        = select email from mailman_recipients where email = '%s'

mx_tls:
  create: false
  name: mx_tls
  data:
    tls_key: |
      -----BEGIN EC PRIVATE KEY-----
      ...
      -----END EC PRIVATE KEY-----
    tls_crt: |
      -----BEGIN CERTIFICATE-----
      ...
      -----END CERTIFICATE-----


postfix:
  hostname: mx.mydomain.com
  mynetworks:
    - 127.0.0.0/8
    - 10.0.0.0/8
  smtpd_recipient_restrictions:
    - reject_authenticated_sender_login_mismatch
    - permit_sasl_authenticated
    - permit_mynetworks
    - reject_unlisted_recipient
  smtpd_relay_restrictions:
    - permit_mynetworks
    - permit_sasl_authenticated
    - reject_unauth_destination

  transport_maps:
    "pgsql:/etc/postfix/pgsql-transport.cf":
      existingSecretName: pgsql-transport
      existingSecretKey: pgsql-transport.cf
    "pgsql:/etc/postfix/pgsql-transport-mm.cf":
      existingSecretName: pgsql-transport-mm
      existingSecretKey: pgsql-transport-mm.cf
  relay_domains:
    "pgsql:/etc/postfix/pgsql-relay-domains-mm.cf":
      existingSecretName: pgsql-relay-domains-mm
      existingSecretKey: pgsql-relay-domains-mm.cf
    "pgsql:/etc/postfix/pgsql-relay-domains.cf":
      existingSecretName: pgsql-relay-domains
      existingSecretKey: pgsql-relay-domains.cf
  relay_recipient_maps:
    "pgsql:/etc/postfix/pgsql-mailman-recipients.cf":
      existingSecretName: pgsql-mailman-recipients
      existingSecretKey: pgsql-mailman-recipients.cf
    "pgsql:/etc/postfix/pgsql-virtual-recipients.cf":
      existingSecretName: pgsql-virtual-recipients
      existingSecretKey: pgsql-virtual-recipients.cf
  virtual_alias_maps:
    "pgsql:/etc/postfix/pgsql-virtual.cf":
      existingSecretName: pgsql-virtual
      existingSecretKey: pgsql-virtual.cf


  tlsEnabled: true
  tlsExistingSecretName: mx_tls
  helo_checks:
    - name: localhost
      action: REJECT
    - name: localhost.localdomain
      action: REJECT
    - name: 127.0.0.1
      action: REJECT
    - name: [127.0.0.1]
      action: REJECT
    - name: User
      action: REJECT
  envelope_sender_checks:
    - name: postmaster@mx.slush.ca
      allow: dene@slush.ca
  milters_active: false
  smtpd_milters:
    - inet:[rspamd]:11332
  non_smtpd_milters:
    - inet:[rspamd]:11332

persistence:
  # -- Enable persistence using Persistent Volume Claims
  # ref: http://kubernetes.io/docs/user-guide/persistent-volumes/.
  # It can be used to store TLS certificates along with `certificatesResolvers.<name>.acme.storage`  option
  sasl:
    enabled: false
    name: sasl
    existingClaim: ""
    accessMode: ReadWriteOnce
    size: 128Mi
    storageClass: ""
    volumeName: ""
    path: /etc/sasl2
    annotations: {}
    # -- Only mount a subpath of the Volume into the pod
    subPath: ""
  queue:
    enabled: false
    name: queue
    existingClaim: ""
    accessMode: ReadWriteOnce
    size: 128Mi
    storageClass: ""
    volumeName: ""
    path: /var/spool/postfix
    annotations: {}
    # -- Only mount a subpath of the Volume into the pod
    subPath: ""

# Default values for postfix.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# This will set the replicaset count more information can be found here: https://kubernetes.io/docs/concepts/workloads/controllers/replicaset/
replicaCount: 1

# This sets the container image more information can be found here: https://kubernetes.io/docs/concepts/containers/images/
image:
  repository: ghcr.io/denefoster/k8s-postfix
  # This sets the pull policy for images.
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""

# This is for the secrets for pulling an image from a private repository more information can be found here: https://kubernetes.io/docs/tasks/configure-pod-container/pull-image-private-registry/
imagePullSecrets: []
# This is to override the chart name.
nameOverride: ""
fullnameOverride: ""

# This section builds out the service account more information can be found here: https://kubernetes.io/docs/concepts/security/service-accounts/
serviceAccount:
  # Specifies whether a service account should be created.
  create: true
  # Automatically mount a ServiceAccount's API credentials?
  automount: true
  # Annotations to add to the service account.
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template.
  name: ""

# This is for setting Kubernetes Annotations to a Pod.
# For more information checkout: https://kubernetes.io/docs/concepts/overview/working-with-objects/annotations/
podAnnotations: {}
# This is for setting Kubernetes Labels to a Pod.
# For more information checkout: https://kubernetes.io/docs/concepts/overview/working-with-objects/labels/
podLabels: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

# This is for setting up a service more information can be found here: https://kubernetes.io/docs/concepts/services-networking/service/
service:
  # This sets the service type more information can be found here: https://kubernetes.io/docs/concepts/services-networking/service/#publishing-services-service-types
  type: ClusterIP
  # This sets the ports more information can be found here: https://kubernetes.io/docs/concepts/services-networking/service/#field-spec-ports
  port: 80

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

# This section is for setting up autoscaling more information can be found here: https://kubernetes.io/docs/concepts/workloads/autoscaling/
autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

# Additional volumes on the output Deployment definition.
volumes: []
  # - name: foo
  #   secret:
  #     secretName: mysecret
  #     optional: false

# Additional volumeMounts on the output Deployment definition.
volumeMounts: []
  # - name: foo
  #   mountPath: "/etc/foo"
  #   readOnly: true

nodeSelector: {}

tolerations: []

affinity: {}
